deco-sites/fashion

deco.gen.ts
import_map.json
islands/InjectLiveScripts.tsx
islands/LiveControls.tsx

Update live and inspect vs code

---

clients/vtex/checkout.ts
components/ProductCard.tsx
deno.json
import_map.json
islands/FooterAccordion.tsx
islands/ProductInformation.tsx
islands/SearchBar.tsx
routes/api/cart/items.ts
routes/start.tsx
sections/Head.tsx
sections/ProductDetails.tsx
utils.ts
vtexTypes.d.ts

This PR fixes typings for fashion

fix: typings

---

import_map.json
live.ts

This PR adds prefetch tech to fashion starter

feat: Add prefetch

---

fresh.gen.ts
routes/api/searchFacets.ts
sections/SearchControls.tsx

- Exports section `SearchControl`
- Only pass to VTEX IS a pre-selected group of queries

Fix search page with ?pageId

---

components/minicart/Cart.tsx
sdk/cart/useCart.ts

This PR adds pqueue and onVisibilityChange callback to the cart module. More info on loom
https://www.loom.com/share/986cb003a1314b95991a615bccb37b6c

feat: swr like cart

---

components/minicart/Cart.tsx

feat: Support coupon on minicart

---

components/menu/Menu.tsx
components/menu/MenuButton.tsx
components/menu/MenuModal.tsx
components/menu/NavItem.ts
fresh.gen.ts
islands/MenuButton.tsx
islands/MenuModal.tsx
sdk/useUI.ts
sections/Header.tsx

Add menu on mobile for fashion

feat: add menu on mobile

---

components/product/ProductCard.tsx
components/product/ProductShelf.tsx
components/search/Searchbar.tsx
components/ui/Highlights.tsx
components/ui/Slider.tsx

feat: Hightlight | DS

---

components/ui/BannerCarousel.tsx

click on banner instead of on button

feat: clickable banner

---

components/header/Header.tsx
components/product/ProductDetails.tsx
components/product/ProductGallery.tsx
components/product/ProductShelf.tsx
components/search/Controls.tsx
components/search/Searchbar.tsx
fresh.gen.ts
import_map.json

As title says. More info at: https://github.com/deco-sites/std/pull/9

feat: Prevent stores from exploding when IS api is not available.

---

components/header/Buttons.tsx
components/header/Header.tsx
components/header/HeaderSearchMenu.tsx
components/header/Modals.tsx
components/header/Navbar.tsx
components/minicart/Cart.tsx
components/minicart/CartItem.tsx
components/minicart/Coupon.tsx
components/search/SearchTermList.tsx
components/search/Searchbar.tsx
components/ui/Loading.tsx
components/ui/Modal.tsx
fresh.gen.ts
import_map.json
islands/HeaderSearchMenu.tsx
routes/api/[...catchall].tsx
sdk/useAddToCart.ts

This pr adds the search terms suggestion for the search.
To this feature works well this needs the [configVTEX loader](https://github.com/deco-sites/std/pull/7) and VTEX Intelligent Search app installed, if the loaders isn't present or the vtex is app isn't installed, the search feature won't add search suggestions.
[preview with the loader pageId=3406](https://deco-sites-fashion-jpqk8aw7ez9g.deno.dev/?pageId=3406)
[preview without](https://deco-sites-fashion-jpqk8aw7ez9g.deno.dev/)

feat: vtex search autocomplete

---

components/header/HeaderSearchMenu.tsx
components/search/SearchTermList.tsx
components/search/Searchbar.tsx

Fix products from search autocomplete when products from loader is nullable (undefined, null)

fix: Products at search autocomplete product 

---

fresh.gen.ts
import_map.json

Add canonical tags to PDP, PLP. Home can be added via CMS
Make sure the <link rel="canonical" /> is present on these pages and these links exist

feat: Canonicals

---

import_map.json

Upgrades std: https://github.com/deco-sites/std/pull/23

chore: upgrade std@0.3.1

---

import_map.json
routes/api/[...catchall].tsx

This PR upgrades denoland/std since our contribution was merged and released. 
Make sure orderForm cookie is now correctly formatted and forwarded. (it is now)

chore: Upgrade denoland/std

---

components/product/ProductGallery.tsx

Fixes some issues regarding lighthouse reports on best practices and SEO.
Before:
After:

fix buttons do not have discernible name

---

components/ui/BannerPLP.tsx
fresh.gen.ts
sections/BannerPLP.tsx

This PR adds a new section regarding PLP's banners.
Open /masculino or /feminino and check that you see the banner. Also, check PSI

feat: Add banner PLP section

---

components/product/ProductCard.tsx

Fix the hydration here: https://deco-sites-fashion-n3tq98yqs17g.deno.dev/feminino
added at this PR #108 
Open `/feminino` and see no errors related to hydration

fix: SearchResult ProductCards hydration

---

import_map.json

Bump live rc58

---

import_map.json
live.gen.ts
schemas.gen.json

Use entrypoint separetely from state

---

routes/_app.tsx
schemas.gen.json
sections/DesignSystem.tsx

Adds a default DesignSystem on _app.tsx

feat: Add defaults

---

import_map.json
schemas.gen.json

Bump live version

---

components/ui/LinkTree.tsx

Adding gap

---

components/ui/LinkTree.tsx

Reverts deco-sites/fashion#174

Revert "Adding gap"

---

import_map.json

Bump live to @1.0.5 enabling LivePageEditor

feat: Inline Editor

---

components/product/ProductCard.tsx
import_map.json
live.gen.ts
schemas.gen.json

Fix product card link

---

import_map.json

chore: Bump live with inline editor

---

sections/BannerGrid.tsx
sections/BannerPLP.tsx
sections/Carousel.tsx
sections/Features.tsx
sections/Footer.tsx
sections/Header.tsx
sections/Highlights.tsx
sections/LinkTree.tsx
sections/ProductDetails.tsx
sections/ProductShelf.tsx
sections/SearchResult.tsx
sections/WhatsApp.tsx
sections/WishlistGallery.tsx

Replace export on sections for better uniformity

feat: export default on sections

---

components/footer/Newsletter.tsx
components/product/OutOfStock.tsx
components/product/ProductDetails.tsx
import_map.json
islands/OutOfStock.tsx
live.gen.ts
schemas.gen.json
sdk/useOffer.ts

add outofstock

---

import_map.json
schemas.gen.json

upgrade std

---

components/footer/Newsletter.tsx
components/minicart/Coupon.tsx
components/search/Sort.tsx
components/ui/Avatar.tsx
components/ui/Breadcrumb.tsx
components/ui/LinkTree.tsx

feat: remove tokens

---

import_map.json

This PR uses deco-cx fresh. With this, I hope to have more stable builds

use forked fresh

---

import_map.json
live.gen.ts
schemas.gen.json

chore: Bump live

---

sections/MeasurementModal.alt+f4.tsx

[Alt+f4 time 169]

---

sections/Testimonials/Testimonials.team-259.tsx

Category 3: Testimonials section
- Admin preview url: https://deco.cx/admin/sites/fashion/blocks/previews?ref=%23%2Fdefinitions%2FZGVjby1zaXRlcy9mYXNoaW9uL3NlY3Rpb25zL1Rlc3RpbW9uaWFscy9UZXN0aW1vbmlhbHMudGVhbS0yNTkudHN4&type=Testimonials
Variant 1:
- Desktop: https://www.figma.com/file/T4oBjZSaiahuqaAQA8ihls/Deco-Hackathon-III-%E2%80%A2--Blocks-Library?type=design&node-id=378-33147&t=x7cvM4CgCRW88WVw-0
- Mobile: https://www.figma.com/file/T4oBjZSaiahuqaAQA8ihls/Deco-Hackathon-III-%E2%80%A2--Blocks-Library?type=design&node-id=378-35534&t=x7cvM4CgCRW88WVw-4

[Team 259] - Testimonials Section

---

schemas.gen.json
sections/DesignSystem/DesignSystem.tsx

Change design system structure

---

schemas.gen.json

chore: update schema.json

---

components/product/ProductCard.tsx
import_map.json

related to: https://github.com/deco-cx/deco/pull/308

feat: upgrade deps

---

import_map.json
live.gen.ts
schemas.gen.json

- Revert "Update live ver"
Revert live version due to issues on schema validation.
Open console when using fashion in admin.

revert update live ver

---

import_map.json
live.gen.ts
schemas.gen.json

Use new resolver version

---

README.md
import_map.json

Force redeploy

---

import_map.json
live.gen.ts

chore: Bump dependencies

---

components/header/Header.tsx
components/product/ProductDetails.tsx
components/product/ProductShelf.tsx
components/search/SearchResult.tsx
live.gen.ts

Remove loader return type

---

components/GlobalTags.tsx
components/ui/Modal.tsx
import_map.json
static/dialog-polyfill.css

This PR bumps deco-cx/fresh that fixes the hydration and fix the dialog polyfill

fix: iphone hydration

---

components/footer/Footer.tsx
components/footer/Newsletter.tsx
components/header/Drawers.tsx
components/header/Searchbar.tsx
components/product/AddToCartButton.tsx
components/product/OutOfStock.tsx
components/product/ProductDetails.tsx
components/product/ProductImageZoom.tsx
components/search/Controls.tsx
components/ui/SliderJS.tsx
components/wishlist/WishlistButton.tsx
islands/AddToCartButton.tsx
islands/Header/Buttons.tsx
islands/Header/Drawers.tsx
islands/Header/Searchbar.tsx
islands/Newsletter.tsx
islands/OutOfStock.tsx
islands/ProductImageZoom.tsx
islands/SearchControls.tsx
islands/ShippingSimulation.tsx
islands/SliderJS.tsx
islands/WishlistButton.tsx
schemas.gen.json

Do not use export default since it's buggy

fix: migrate islands

---

import_map.json
schemas.gen.json

chore: bump deco

---

import_map.json

chore: Bump std

---

components/footer/Logo.tsx
components/footer/MobileApps.tsx

feat: Defer footer imgs

---

import_map.json
live.gen.ts
schemas.gen.json

more info at: https://github.com/deco-sites/std/pull/171

feat: Same domain images

---

import_map.json
live.gen.ts

- Bump deco to 1.27.9.
- Gens.

Bump deco to 1.27.9

---

import_map.json
live.gen.ts

Bump fashion std to 1.20.11.
